name: 'ESP32 Rust CI'
description: 'Set up Rust toolchain for ESP32.'
runs:
  using: "composite"
  steps:
    - name: Python setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8
      
    - name: Install libclang
      shell: bash
      run: sudo apt update && sudo apt-get install clang libclang-dev -y
      
    - name: Rust setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.rust_toolchain }}
        components: rustfmt, clippy #, rust-src
        default: true
    
    - name: Install `rust-src`
      shell: bash
      run: rustup component add rust-src --toolchain ${{ env.rust_toolchain }}-x86_64-unknown-linux-gnu
    
    - name: Install `ldproxy`
      uses: actions-rs/install@v0.1
      with:
        crate: ldproxy
        version: latest
        use-tool-cache: true
      continue-on-error: true